package:
  name: openalea.components
  version: nightly

source:
  git_url: https://github.com/openalea/openalea-components
  git_tag: develop


build:
  preserve_egg_dir: True
  number: 1

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
    - openalea.misc ==nightly
    - openalea.core ==nightly
  run:
    - python
    - setuptools
    - openalea.deploy
    - openalea.misc ==nightly
    - openalea.core ==nightly
    - numpy
    - scipy
    - matplotlib

test:
  imports:
    - openalea.math

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-C License
