package:
  name: openalea.grapheditor
  version: nightly

source:
  git_url: https://github.com/openalea/openalea
  git_tag: develop

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools
    - openalea.deploy
    - openalea.core ==nightly
    - openalea.vpltk ==nightly
    - pyqt <=4.11

test:
  imports:
    - openalea.grapheditor.all

about:
  home: http://virtualplants.github.io
  license: Cecill-C License
