package:
  name: openalea.visualea
  version: 1.3.0

source:
  git_url: https://github.com/openalea/openalea
#  git_url: ../../../git/openalea

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
    - openalea.core
    - openalea.grapheditor
    - mingw # [win]
  run:
    - python
    - setuptools
    - openalea.core
    - openalea.grapheditor
    - pyqt
    - ipython =2.4.1
about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-C License