package:
  name: openalea.visualea
  version: 1.3.0

source:
  git_url: https://github.com/openalea/openalea
  git_tag: install_requires

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
    - mingw # [win]

  run:
    - python
    - setuptools
    - openalea.deploy
    - openalea.core
    - openalea.misc
    - openalea.vpltk
    - openalea.grapheditor
    - openalea.oalab
    - pyqt
    - ipython ==2.4.1
    - ipython-qtconsole ==2.4.1

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-C License