package:
  name: openalea.vpltk
  version: 2.0.0

source:
  git_url: https://github.com/openalea/openalea

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools
    - pyqt

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-C License