package:
  name: openalea.vpltk
  version: 1.3.0

source:
  git_url: https://github.com/openalea/openalea

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-C License