package:
  name: openalea.oalab
  version: nightly

source:
  git_url: https://github.com/openalea/openalea
  git_tag: develop

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools
    - openalea.deploy
    - openalea.core ==nightly
    - openalea.vpltk ==nightly
    - openalea.grapheditor ==nightly
    - openalea.visualea ==nightly

about:
  home: http://virtualplants.github.io
  license: Cecill License
