package:
  name: openalea.oalab
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/openalea/openalea
  git_tag: master

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools
    - openalea.deploy
    - openalea.core
    - openalea.vpltk
    - openalea.grapheditor
    - openalea.visualea

about:
  home: http://virtualplants.github.io
  license: Cecill License
