package:
  name: vplants.sequence_analysis
  version: 1.2.0

source:
  git_url: https://github.com/VirtualPlants/StructureAnalysis

about:
  home: http://openalea.gforge.inria.fr
  license: GPL/LGPL
  summary: Tool for stat and sequence analysis

build:
  preserve_egg_dir: True

requirements:
  # it doesn't really require python, but maybe that will fix
  # the missing bin directory
  build:
   - python
   - setuptools
   - openalea.deploy
   - scons
   - openalea.sconsx
   - readline
   - qt
   - vplants.tool
   - vplants.stat_tool
   - boost
  run:
   - python
   - readline
   - qt
   - vplants.tool
   - vplants_stat_tool
