package:
  name: vplants.tool
  version: 1.2.0

source:
  path: ../../../git/StructureAnalysis/tool

about:
  home: http://openalea.gforge.inria.fr
  license: GPL/LGPL
  summary: Tool for stat and sequence analysis

# needs boost - this is now in defaults.  the ioos boost is broken (and has been
# deprecated but still appears in the channel - 2015-08-02)

requirements:
  # it doesn't really require python, but maybe that will fix
  # the missing bin directory
  build:
   - openalea.sconsx
   - openalea.deploy
   - python
   - scons
   - readline
   - qt
  run:
   - readline
   - qt
