package:
  name: openalea.oalab
  version: 1.3.0

source:
  git_url: https://github.com/openalea/openalea
#  git_url: ../../../git/openalea
  git_tag: conda

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
    - openalea.visualea
  run:
    - python
    - setuptools
    - openalea.visualea

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill License