package:
  name: openalea.oalab
  version: 1.3.0

source:
  git_url: https://github.com/openalea/openalea

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools
    - openalea.deploy
    - openalea.core
    - openalea.vpltk
    - openalea.grapheditor
    - openalea.visualea

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill License