package:
  name: openalea.misc
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/openalea/openalea
  git_tag: master

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools
    - openalea.deploy
    - sphinx

test:
  imports:
    - openalea.misc

about:
  home: http://virtualplants.github.io
  license: Cecill-C License
