package:
  name: openalea.sconsx
  version: 2.0.0

source:
  git_url: https://github.com/openalea/sconsx

requirements:
  build:
    - python
    - openalea.deploy
  run:
    - python
    - scons

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-c License
