package:
  name: openalea.sconsx
  version: 1.3.0

source:
  git_url: https://github.com/openalea/sconsx
  # git_tag: builddir
  # path : /Users/pradal/devlp/git/openalea/sconsx
requirements:
  build:
    - python
    - openalea.deploy
  run:
    - python
    - scons

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-c License
