package:
  name: openalea.sconsx
  version: 1.2.1

source:
  git_url: https://github.com/pradal/sconsx
  git_tag: conda
  # path : /Users/pradal/devlp/git/openalea/sconsx
requirements:
  build:
    - python
    - openalea.deploy
  run:
    - python
    - scons

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-c License