package:
  name: openalea.visualea
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/openalea/openalea
  git_tag: install_requires

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
    #- mingw # [win]

  run:
    - python
    - setuptools
    - openalea.deploy
    - openalea.core
    - openalea.misc
    - openalea.vpltk
    - openalea.grapheditor
    - openalea.oalab
    - qt <5
    - pyqt <5
    - ipython ==2.4.1
    - ipython-qtconsole ==2.4.1

about:
  home: http://virtualplants.github.io
  license: Cecill-C License
