package:
  name: openalea.grapheditor
  version: 1.3.0

source:
  git_url: https://github.com/openalea/openalea
#  git_url: ../../../git/openalea
  git_tag: conda

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-C License