package:
  name: openalea.deploy
  version: 1.2.1

source:
  git_url: https://github.com/pradal/deploy
  git_tag: conda
#  git_url: ../../../git/deploy
  # git_url: /Users/pradal/devlp/git/deploy
  # git_tag: conda

build:
  number: 3

requirements:
  build:
    - python
    - setuptools
    - pywin32 # [win]
  run:
    - python
    - setuptools
    - pywin32 # [win]

test:
  imports:
    - openalea.deploy

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-c License