package:
  name: openalea.deploy
  version: 1.2.1

source:
  git_url: https://github.com/pradal/deploy
  git_tag: conda
#  git_url: ../../../git/deploy

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - openalea.deploy

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-c License