package:
  name: openalea.misc
  version: 1.3.0

source:
  git_url: https://github.com/openalea/openalea

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - openalea.deploy
    - sphinx

test:
  imports:
    - openalea.misc

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-C License