package:
  name: openalea.vpltk
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/openalea/openalea
  git_tag: develop

build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools
    - pyqt

about:
  home: http://virtualplants.github.io
  license: Cecill-C License
